### ISSUE TITLE
mini_portile2 will not run on Ruby 3.1.0.dev (master) where net-ftp is a bundled gem

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/mini_portile#101]
When using mini_portile2 on Ruby 3.1.0.dev, we see this error:

```
/home/runner/work/nokogiri/nokogiri/vendor/bundle/ruby/3.1.0/gems/mini_portile2-2.5.1/lib/mini_portile2/mini_portile.rb:4:in `require': cannot load such file -- net/ftp (LoadError)
	from /home/runner/work/nokogiri/nokogiri/vendor/bundle/ruby/3.1.0/gems/mini_portile2-2.5.1/lib/mini_portile2/mini_portile.rb:4:in `<top (required)>'
	from /home/runner/work/nokogiri/nokogiri/vendor/bundle/ruby/3.1.0/gems/mini_portile2-2.5.1/lib/mini_portile2.rb:2:in `require'
	from /home/runner/work/nokogiri/nokogiri/vendor/bundle/ruby/3.1.0/gems/mini_portile2-2.5.1/lib/mini_portile2.rb:2:in `<top (required)>'
	from ../../../../ext/nokogiri/extconf.rb:402:in `require'
	from ../../../../ext/nokogiri/extconf.rb:402:in `process_recipe'
	from ../../../../ext/nokogiri/extconf.rb:871:in `<main>'
```

Recent commits on Ruby master (e.g., https://github.com/ruby/ruby/commit/e49c998d1e41737016c8afb7e1b22797018caebb) moved the `net-*` set of libraries from the standard library to be bundled gems.

I'm creating this issue to:

- [x] add ruby-head to the set of rubies being tested in CI
- [x] address the above error (and any other related errors)

**Comment by flavorjones** [comment]
Fixed in v2.5.2.

**Comment by KartikSoneji** [comment]
Hi, apologies if `v2.4.0` is not supported but I couldn't find any info on supported versions.

While working on another package ([asciidoctor](https://github.com/asciidoctor/asciidoctor)), I noticed installing `nokogiri@1.10.10` breaks on ruby 3.1 since it [depends on `mini_portile2@2.4.0`](https://github.com/sparklemotion/nokogiri/blob/a9a3717154bdb99ed6d0d785736eb471c9d6a954/Rakefile#L138), which has this issue.

I'm not too familiar with ruby, but it seems this can be fixed:
- by nokogiri:
  - release `nokogiri@1.10.11` with `net-ftp` as a dependency
  - release `nokogiri@1.10.11` using `mini_portile2~>2.5.0`
- by mini_portile:
  - release `mini_portile2@2.4.1` with `net-ftp` as a dependency
 
I'm not sure which fix would be best, but I'll be happy to open a PR in whichever repo it should go to.
Unless both `nokogiri@1.10.10` and `mini_portile2@2.4.0` are no longer supported, in which case I'll open an issue in asciidoctor.
Thanks.

**Comment by flavorjones** [comment]
Hi! Nokogiri v1.10 is not a supported version, since v1.11 was released in January 2021 (the current supported branch is v1.13.x). Please ask the asciidoctor maintainers to update the gemspec!

**Comment by flavorjones** [comment]
I actually did this while I had context swapped in: https://github.com/asciidoctor/asciidoctor/pull/4339

**Comment by KartikSoneji** [comment]
Hi @flavorjones 

> Nokogiri v1.10 is not a supported version, since v1.11 was released in January 2021

Got it.

> I actually did this while I had context swapped in: https://github.com/asciidoctor/asciidoctor/pull/4339
Thanks!
