### ISSUE TITLE
Checksums should be verified at extraction time (in addition to download time)

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/mini_portile#56]
I'd like to eliminate the possibility that files are being changed on disk after download, but before extraction (particularly because downloaded files are cached and used later if the compiled version is removed).

I would like to re-use the same checksum verification logic that's currently being used at download time.

**Comment by larskanis** [comment]
I vote against eliminating the possibility that files are being changed on disk after download. This is something I do sometimes while development.

I implemented it that way, at first, but changed it to only check at download time, eventually. I did this, because the purpose of the digest value is to make insecure network transfer trustworthy. But the local file system is something we must trust per definition. This the case in particular after the tar file is extracted. There is no mechanism that checks any file integrity, then.

**Comment by flavorjones** [comment]
@larskanis Ordinarily I'd agree, but right now the following can happen:

1. download a file that's corrupt or has been maliciously changed
2. see a failure of some sort
3. re-run the build using the corrupt/malicious file on disk
4. extraction goes fine and build proceeds

This is why I feel strongly we should verify files on disk before extraction.

**Comment by flavorjones** [comment]
@larskanis note that I've put a commit on `master` that addresses my concerns.

**Comment by larskanis** [comment]
You're right and it LGTM. Thanks!
