### ISSUE TITLE
Appveyor CI is failing. Fix it!

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/mini_portile#92]
See https://ci.appveyor.com/project/flavorjones/mini-portile/branch/master

**Comment by larskanis** [comment]
Alright sir - will do!

**Comment by larskanis** [comment]
There is an issue: Since commit bbe88319194a249e13af4b9d2e39f7dab1f581c1 Gemfile depends on bundler-2.1.x, but gemspec still [declares compatibility to ruby-1.9.2](https://github.com/flavorjones/mini_portile/blob/0aa7e978e3b63d701276accfcb6d87a4911c304f/mini_portile2.gemspec#L41). Unfortunately bundler-2.x doesn't work on ruby<2.3 .
I'll increase the ruby version requirement.
